var data = {
    "code": 0,
    "msg": "success",
    "data": [{
        "topic": "（单选题）2020年乔雅登家族中雅致的定位：",
        "label": "新开机构",
        "correct": "D",
        "options": [{
            "letter": "A",
            "content": "大牌经典款"
        }, {
            "letter": "B",
            "content": "大牌旗舰款"
        }, {
            "letter": "C",
            "content": "自然融合，致美天成"
        }, {
            "letter": "D",
            "content": "大牌基本款"
        }]
    }, {
        "topic": "（多选题）乔雅登<sup>®</sup>极致的产品特性包括 ",
        "label": "产品知识",
        "correct": "ABC",
        "options": [{
            "letter": "A",
            "content": "优越的提升能力"
        }, {
            "letter": "B",
            "content": "维持时间超过1年"
        }, {
            "letter": "C",
            "content": "自然融合"
        }, {
            "letter": "D",
            "content": "低内聚力"
        }]
    }, {
        "topic": "（单选题）HYLACROSS™ 技术采用以下哪种方法得到柔顺均质的凝胶？",
        "label": "产品知识",
        "correct": "B",
        "options": [{
            "letter": "A",
            "content": "颗粒筛分技术"
        }, {
            "letter": "B",
            "content": "均质化"
        }, {
            "letter": "C",
            "content": "分子鳌合技术"
        }, {
            "letter": "D",
            "content": "膜分离技术"
        }]
    }, {
        "topic": "（多选题）邀约上门方案三要素：",
        "label": "沙龙十步法",
        "correct": "ABC",
        "options": [{
            "letter": "A",
            "content": "简单易懂少套路"
        }, {
            "letter": "B",
            "content": "实惠有诱惑"
        }, {
            "letter": "C",
            "content": "普遍有需求"
        }, {
            "letter": "D",
            "content": "越优惠越好"
        }]
    }, {
        "topic": "（单选题）以下哪项不是中端玻尿酸市场的痛点：",
        "label": "雅计划院内执行",
        "correct": "A",
        "options": [{
            "letter": "A",
            "content": "产品种类多"
        }, {
            "letter": "B",
            "content": "价格不稳定"
        }, {
            "letter": "C",
            "content": "渠道管控乱"
        }, {
            "letter": "D",
            "content": "品牌支撑弱"
        }]
    }, {
        "topic": "（多选题）专场沙龙培训形式节奏：",
        "label": "沙龙十步法",
        "correct": "ABCD",
        "options": [{
            "letter": "A",
            "content": "专场前至少两次以上培训、专场当天要专家培训"
        }, {
            "letter": "B",
            "content": "优秀咨询医生分享会"
        }, {
            "letter": "C",
            "content": "专场前WORKSHOP讨论解决大家障碍点，融动全院氛围"
        }, {
            "letter": "D",
            "content": "咨询实战演练点评式培训"
        }]
    }, {
        "topic": "（单选题）某新开机构首月进货50盒，可以拿到多少进货折扣？",
        "label": "新开机构",
        "correct": "A",
        "options": [{
            "letter": "A",
            "content": "16%"
        }, {
            "letter": "B",
            "content": "18%"
        }, {
            "letter": "C",
            "content": "20%"
        }, {
            "letter": "D",
            "content": "22%"
        }]
    }, {
        "topic": "（多选题）关于乔雅登<sup>®</sup>系列组织融合的说法正确的是？",
        "label": "产品知识",
        "correct": "ABC",
        "options": [{
            "letter": "A",
            "content": "注射效果更自然"
        }, {
            "letter": "B",
            "content": "注射后无异物感"
        }, {
            "letter": "C",
            "content": "动物实验组织切片显示凝胶在组织中的分布均匀更容易推注"
        }, {
            "letter": "D",
            "content": "动物实验组织切片显示凝胶内有组织的长入"
        }]
    }, {
        "topic": "（多选题）如何达到好的线上线下露出的效果：",
        "label": "沙龙十步法",
        "correct": "ABCD",
        "options": [{
            "letter": "A",
            "content": "活动前1周、3天、2天、1天、当天等最好全院全员转发"
        }, {
            "letter": "B",
            "content": "提前一周院内布置出大气、显眼的单一乔雅登元素"
        }, {
            "letter": "C",
            "content": "当天要实时播放销售战况，营造爆场氛围"
        }, {
            "letter": "D",
            "content": "参杂其他院内的活动一起摆放，活动当天忙于事物流程就好。"
        }]
    }, {
        "topic": "（单选题）通常来说，管理层对于雅致转换中端玻尿酸的盈利测算底线是：",
        "label": "雅计划院内执行",
        "correct": "C",
        "options": [{
            "letter": "A",
            "content": "业绩增长"
        }, {
            "letter": "B",
            "content": "利润增加"
        }, {
            "letter": "C",
            "content": "业绩增长，利润不亏"
        }, {
            "letter": "D",
            "content": "提升机构品牌度"
        }]
    }, {
        "topic": "（多选题）乔雅登<sup>®</sup>雅致的产品特性包括 ",
        "label": "产品知识",
        "correct": "ABCD",
        "options": [{
            "letter": "A",
            "content": "均质型凝胶，柔顺平滑"
        }, {
            "letter": "B",
            "content": "与注射层次匹配的支撑性"
        }, {
            "letter": "C",
            "content": "长效持久"
        }, {
            "letter": "D",
            "content": "适合软组织填充"
        }]
    }, {
        "topic": "（单选题）下列哪项不属于乔雅登<sup>®</sup>Hylacross™系列产品特性？",
        "label": "产品知识",
        "correct": "D",
        "options": [{
            "letter": "A",
            "content": "稳健凝聚的三维基质"
        }, {
            "letter": "B",
            "content": "柔顺匀质"
        }, {
            "letter": "C",
            "content": "临床效果持久"
        }, {
            "letter": "D",
            "content": "相对低浓度透明质酸"
        }]
    }, {
        "topic": "（单选题）以下产品在相同测试条件下，内聚力最高的是____, ",
        "label": "产品知识",
        "correct": "A",
        "options": [{
            "letter": "A",
            "content": "乔雅登极致"
        }, {
            "letter": "B",
            "content": "乔雅登雅致"
        }, {
            "letter": "C",
            "content": "瑞蓝"
        }, {
            "letter": "D",
            "content": "瑞蓝perlane"
        }]
    }, {
        "topic": "（多选题）顾客邀约跟进三要素：",
        "label": "沙龙十步法",
        "correct": "ABC",
        "options": [{
            "letter": "A",
            "content": "谁跟进：咨询主管第一责任人"
        }, {
            "letter": "B",
            "content": "跟进节奏：提前一周开始，每天早晚会跟"
        }, {
            "letter": "C",
            "content": "跟进工具和内容：统一邀约话术，表格，跟进到每一个邀约顾客具体情况"
        }, {
            "letter": "D",
            "content": "跟进邀约数量，统计邀约顾客数量越多越有保障"
        }]
    }, {
        "topic": "（单选题）有关G’值的描述错误的是？",
        "label": "产品知识",
        "correct": "C",
        "options": [{
            "letter": "A",
            "content": "反映了材料本身的机械坚固性"
        }, {
            "letter": "B",
            "content": "G’值与内聚力的均衡配比提供乔雅登优越的提升能力"
        }, {
            "letter": "C",
            "content": "G‘值越高越好"
        }, {
            "letter": "D",
            "content": "与“弹性模量”的概念相同"
        }]
    }, {
        "topic": "（单选题）乔雅登<sup>®</sup>系列雅致的透明质酸浓度为多少？",
        "label": "产品知识",
        "correct": "D",
        "options": [{
            "letter": "A",
            "content": "12mg/ml"
        }, {
            "letter": "B",
            "content": "16mg/ml"
        }, {
            "letter": "C",
            "content": "20mg/ml"
        }, {
            "letter": "D",
            "content": "24mg/ml"
        }]
    }, {
        "topic": "（单选题）乔雅登<sup>®</sup>系列使用的交联剂是下列选项中的哪一个？",
        "label": "产品知识",
        "correct": "A",
        "options": [{
            "letter": "A",
            "content": "4-丁二醇二羧酸甘油醚（BDDE）"
        }, {
            "letter": "B",
            "content": "二乙烯基砜"
        }, {
            "letter": "C",
            "content": "DVS"
        }, {
            "letter": "D",
            "content": "EDGMA"
        }]
    }, {
        "topic": "（多选题）如何评价透明质酸填充剂提升能力：",
        "label": "产品知识",
        "correct": "ABCD",
        "options": [{
            "letter": "A",
            "content": "体外实验的定量参数，弹性模量G’、内聚力"
        }, {
            "letter": "B",
            "content": "直观定性试验，载玻片实验"
        }, {
            "letter": "C",
            "content": "动物研究"
        }, {
            "letter": "D",
            "content": "人体研究"
        }]
    }, {
        "topic": "（单选题）判断一位医生在院内影响力的最有效方法是：",
        "label": "雅计划院内执行",
        "correct": "D",
        "options": [{
            "letter": "A",
            "content": "管理层重视度"
        }, {
            "letter": "B",
            "content": "跟艾尔建的合作度"
        }, {
            "letter": "C",
            "content": "自身学术和技术水平"
        }, {
            "letter": "D",
            "content": "咨询师输送顾客的数量和质量"
        }]
    }, {
        "topic": "（多选题）写出乔雅登<sup>®</sup>极致和乔雅登<sup>®</sup>雅致的注射技术 ",
        "label": "产品知识",
        "correct": "ABC",
        "options": [{
            "letter": "A",
            "content": "情绪美学"
        }, {
            "letter": "B",
            "content": "MDCodes注射技术"
        }, {
            "letter": "C",
            "content": "MD ASA"
        }, {
            "letter": "D",
            "content": "韧带提拉打法"
        }, {
            "letter": "E",
            "content": "Medical Highlighting"
        }]
    }, {
        "topic": "（单选题）透明质酸交联剂BDDE的残留量的安全标准是 ",
        "label": "产品知识",
        "correct": "A",
        "options": [{
            "letter": "A",
            "content": "2ppm"
        }, {
            "letter": "B",
            "content": "1ppm"
        }, {
            "letter": "C",
            "content": "0.5ppm"
        }, {
            "letter": "D",
            "content": "3ppm"
        }]
    }, {
        "topic": "（单选题）以下产品在相同测试条件下，G’值最低的是_____, ",
        "label": "产品知识",
        "correct": "B",
        "options": [{
            "letter": "A",
            "content": "乔雅登极致"
        }, {
            "letter": "B",
            "content": "乔雅登雅致"
        }, {
            "letter": "C",
            "content": "瑞蓝"
        }, {
            "letter": "D",
            "content": "瑞蓝perlane"
        }]
    }, {
        "topic": "（多选题）影响透明质酸凝胶吸水性的因素有 ",
        "label": "产品知识",
        "correct": "ABCD",
        "options": [{
            "letter": "A",
            "content": "透明质酸的浓度"
        }, {
            "letter": "B",
            "content": "透明质酸的交联度"
        }, {
            "letter": "C",
            "content": "已交联与未交联透明质酸凝胶的比例"
        }, {
            "letter": "D",
            "content": "透明质酸的生产工艺"
        }]
    }, {
        "topic": "（多选题）关于透明质酸凝胶吸水性的说法，正确的是 ",
        "label": "产品知识",
        "correct": "ABD",
        "options": [{
            "letter": "A",
            "content": "相同生产工艺下，随着交联程度的增加，G 升高，溶胀因子降低"
        }, {
            "letter": "B",
            "content": "一定的吸水性有益于临床实践，增大容积，医生需掌握不同产品的特性以避免矫枉过正或治疗不足"
        }, {
            "letter": "C",
            "content": "临床实践的肿胀程度等于实验中的膨胀系数"
        }, {
            "letter": "D",
            "content": "吸水性所带来的安全性问题，需要看临床数据，目前没有数据显示瑞蓝或菲洛嘉AFU优于乔雅登系列"
        }]
    }, {
        "topic": "（单选题）乔雅登是什么属性的产品：",
        "label": "新开机构",
        "correct": "A",
        "options": [{
            "letter": "A",
            "content": "山猫"
        }, {
            "letter": "B",
            "content": "明星"
        }, {
            "letter": "C",
            "content": "金牛"
        }, {
            "letter": "D",
            "content": "猎狗"
        }]
    }, {
        "topic": "（多选题）有关乔雅登<sup>®</sup>系列临床持久性的描述正确的有:",
        "label": "产品知识",
        "correct": "AB",
        "options": [{
            "letter": "A",
            "content": "3D立体结构不容易降解"
        }, {
            "letter": "B",
            "content": "耐理化因素的能力增强"
        }, {
            "letter": "C",
            "content": "维持时间越长越好"
        }, {
            "letter": "D",
            "content": "可永久存在"
        }]
    }, {
        "topic": "（多选题）有关内聚力的描述错误的是 ",
        "label": "产品知识",
        "correct": "CD",
        "options": [{
            "letter": "A",
            "content": "是材料保持原有形状的能力"
        }, {
            "letter": "B",
            "content": "内聚力和G’值的均衡配比可获得优越的提升能力"
        }, {
            "letter": "C",
            "content": "相同工艺下，浓度越低，内聚力越高"
        }, {
            "letter": "D",
            "content": "内聚力与塑形性无关"
        }]
    }, {
        "topic": "（单选题）2020年乔雅登商业政策季度销量起始盒数是 ",
        "label": "新开机构",
        "correct": "A",
        "options": [{
            "letter": "A",
            "content": "15盒"
        }, {
            "letter": "B",
            "content": "20盒"
        }, {
            "letter": "C",
            "content": "30盒"
        }, {
            "letter": "D",
            "content": "60盒"
        }]
    }, {
        "topic": "（单选题）如何有效推动咨询师执行中端玻尿酸转换：",
        "label": "雅计划院内执行",
        "correct": "D",
        "options": [{
            "letter": "A",
            "content": "设立指标和KPI"
        }, {
            "letter": "B",
            "content": "培训转换话术"
        }, {
            "letter": "C",
            "content": "加强日常跟进"
        }, {
            "letter": "D",
            "content": "以上都是"
        }]
    }, {
        "topic": "（单选题）以下产品在相同测试条件下，G’值最高的是_____, ",
        "label": "产品知识",
        "correct": "D",
        "options": [{
            "letter": "A",
            "content": "乔雅登极致"
        }, {
            "letter": "B",
            "content": "乔雅登雅致"
        }, {
            "letter": "C",
            "content": "瑞蓝"
        }, {
            "letter": "D",
            "content": "瑞蓝perlane"
        }]
    }, {
        "topic": "（单选题）以下产品在相同测试条件下，内聚力最低的是____,",
        "label": "产品知识",
        "correct": "C",
        "options": [{
            "letter": "A",
            "content": "乔雅登极致"
        }, {
            "letter": "B",
            "content": "乔雅登雅致"
        }, {
            "letter": "C",
            "content": "瑞蓝"
        }, {
            "letter": "D",
            "content": "瑞蓝perlane"
        }]
    }, {
        "topic": "（单选题）关于透明质酸安全性说法正确的是",
        "label": "产品知识",
        "correct": "A",
        "options": [{
            "letter": "A",
            "content": "乔雅登<sup>®</sup>系列残留BDDE小于2ppm"
        }, {
            "letter": "B",
            "content": "交联度越低，残留BDDE越少"
        }, {
            "letter": "C",
            "content": "交联剂残留越少，过敏反应发生越少"
        }, {
            "letter": "D",
            "content": "交联剂残留越少，临床安全性越高"
        }]
    }, {
        "topic": "（多选题）在动物实验测试透明质酸凝胶提升能力的实验中，如下说法正确的是 ",
        "label": "产品知识",
        "correct": "ABC",
        "options": [{
            "letter": "A",
            "content": "对于不同的产品组，提升力与G’无明显线性关系"
        }, {
            "letter": "B",
            "content": "对于采用相同的交联技术/生产工艺的产品，总体提升力和G’之间呈线性关系"
        }, {
            "letter": "C",
            "content": "乔雅登极致的总体提升能力优于瑞蓝Perlane"
        }, {
            "letter": "D",
            "content": "单一的G’值等同于提升能力"
        }, {
            "letter": "E",
            "content": "乔雅登丰颜的总体提升能力是最优的"
        }]
    }, {
        "topic": "（多选题）面部解剖的关键层次包含哪些 ",
        "label": "产品知识",
        "correct": "ABCDE",
        "options": [{
            "letter": "A",
            "content": "骨骼"
        }, {
            "letter": "B",
            "content": "深层脂肪垫"
        }, {
            "letter": "C",
            "content": "肌肉"
        }, {
            "letter": "D",
            "content": "皮肤"
        }, {
            "letter": "E",
            "content": "浅层脂肪垫"
        }]
    }, {
        "topic": "（多选题）沙龙主题设置要点：",
        "label": "沙龙十步法",
        "correct": "ABCDE",
        "options": [{
            "letter": "A",
            "content": "季性 根据季节特殊性"
        }, {
            "letter": "B",
            "content": "机构活动节点"
        }, {
            "letter": "C",
            "content": "厂家大活动"
        }, {
            "letter": "D",
            "content": "当下流行潮流"
        }, {
            "letter": "E",
            "content": "终以新颖，美感、吸引求美者为标准"
        }]
    }, {
        "topic": "（多选题）乔雅登家族中雅致的运营属性：",
        "label": "新开机构",
        "correct": "BD",
        "options": [{
            "letter": "A",
            "content": "纳客"
        }, {
            "letter": "B",
            "content": "高值顾客筛选"
        }, {
            "letter": "C",
            "content": "粘客"
        }, {
            "letter": "D",
            "content": "高值顾客升级"
        }]
    }, {
        "topic": "（单选题）判断一家医院的乔雅登潜力，最关键是看：",
        "label": "雅计划院内执行",
        "correct": "C",
        "options": [{
            "letter": "A",
            "content": "医生技术"
        }, {
            "letter": "B",
            "content": "CEO合作度"
        }, {
            "letter": "C",
            "content": "优质存量顾客"
        }, {
            "letter": "D",
            "content": "竞品销量"
        }]
    }, {
        "topic": "（多选题）活动当天运营方案三要素：",
        "label": "沙龙十步法",
        "correct": "ABC",
        "options": [{
            "letter": "A",
            "content": "活动当天要有主打套餐"
        }, {
            "letter": "B",
            "content": "有结合主套餐的KPI激励"
        }, {
            "letter": "C",
            "content": "确认每个咨询清晰理解方案"
        }, {
            "letter": "D",
            "content": "运营做方案就好，咨询自己理解发挥"
        }]
    }, {
        "topic": "（单选题）专场沙龙乔雅登业绩保障的最关键因素是：",
        "label": "沙龙十步法",
        "correct": "D",
        "options": [{
            "letter": "A",
            "content": "院内氛围"
        }, {
            "letter": "B",
            "content": "线上推送"
        }, {
            "letter": "C",
            "content": "方案设置"
        }, {
            "letter": "D",
            "content": "顾客邀约"
        }]
    }, {
        "topic": "（多选题）全院全员动员大会内容包括：",
        "label": "沙龙十步法",
        "correct": "ABC",
        "options": [{
            "letter": "A",
            "content": "方案KPI解读"
        }, {
            "letter": "B",
            "content": "专家资质、特色、配合要点介绍"
        }, {
            "letter": "C",
            "content": "邀约话术、主套餐话术、产品优势等培训"
        }, {
            "letter": "D",
            "content": "跟机构早晚会放在一起，顺便宣导"
        }]
    }, {
        "topic": "（多选题）影响透明质酸填充剂提升能力的因素有：",
        "label": "产品知识",
        "correct": "ABCD",
        "options": [{
            "letter": "A",
            "content": "HA浓度"
        }, {
            "letter": "B",
            "content": "弹性模量G’"
        }, {
            "letter": "C",
            "content": "内聚力"
        }, {
            "letter": "D",
            "content": "生产工艺"
        }]
    }, {
        "topic": "（多选题）如何达到专场后复盘好的销售：",
        "label": "沙龙十步法",
        "correct": "ABC",
        "options": [{
            "letter": "A",
            "content": "及时性，活动结束当天或三天之内"
        }, {
            "letter": "B",
            "content": "不同责任人各自复盘自己负责的对应范畴"
        }, {
            "letter": "C",
            "content": "优点和缺点同时需要具备"
        }, {
            "letter": "D",
            "content": "运营或总经理全部包揽，逐一指出各部门不足之处"
        }]
    }, {
        "topic": "（单选题）某医院的乔雅登顾客复购差，可能的原因是：",
        "label": "雅计划院内执行",
        "correct": "D",
        "options": [{
            "letter": "A",
            "content": "注射效果不满意"
        }, {
            "letter": "B",
            "content": "服务体验不满意"
        }, {
            "letter": "C",
            "content": "医院不重视回访"
        }, {
            "letter": "D",
            "content": "以上都是"
        }]
    }, {
        "topic": "（多选题）有效乔雅登沙龙能起到什么作用？",
        "label": "新开机构",
        "correct": "ABC",
        "options": [{
            "letter": "A",
            "content": "增加机构乔雅登产出"
        }, {
            "letter": "B",
            "content": "提升机构保妥适产出"
        }, {
            "letter": "C",
            "content": "增加机构知名度"
        }, {
            "letter": "D",
            "content": "降低机构员工工作积极性"
        }]
    }, {
        "topic": "（单选题）以下哪项不是设置乔雅登小套餐的主要目的？",
        "label": "雅计划院内执行",
        "correct": "B",
        "options": [{
            "letter": "A",
            "content": "降低咨询师成交门槛"
        }, {
            "letter": "B",
            "content": "降低对注射医生的要求"
        }, {
            "letter": "C",
            "content": "扩大乔雅登体验人群"
        }, {
            "letter": "D",
            "content": "便于聚集管理和跟进"
        }]
    }, {
        "topic": "（单选题）小艾招新会给机构匹配的样品数：",
        "label": "新开机构",
        "correct": "C",
        "options": [{
            "letter": "A",
            "content": "2盒雅致"
        }, {
            "letter": "B",
            "content": "2盒极致"
        }, {
            "letter": "C",
            "content": "1盒极致，1盒雅致"
        }, {
            "letter": "D",
            "content": "1支极致，1支雅致"
        }]
    }, {
        "topic": "（多选题）有效的乔雅登沙龙的专家环节是？",
        "label": "新开机构",
        "correct": "ABCD",
        "options": [{
            "letter": "A",
            "content": "对注射专家的铺垫"
        }, {
            "letter": "B",
            "content": "咨询对专家的信任"
        }, {
            "letter": "C",
            "content": "专家与机构的匹配度"
        }, {
            "letter": "D",
            "content": "专家自身的注射技术与沟通方式"
        }]
    }, {
        "topic": "（单选题）以下哪个不属于“八四三一法则“中的“三条件”？",
        "label": "新开机构",
        "correct": "D",
        "options": [{
            "letter": "A",
            "content": "机构成立5年以上"
        }, {
            "letter": "B",
            "content": "机构流水相对大"
        }, {
            "letter": "C",
            "content": "机构活跃度够强"
        }, {
            "letter": "D",
            "content": "机构占地面积要超过5000平"
        }]
    }, {
        "topic": "（多选题）如何选择合适的透明质酸，说法正确的是 ",
        "label": "产品知识",
        "correct": "ABCDE",
        "options": [{
            "letter": "A",
            "content": "需根据注射层次和需要的矫正程度"
        }, {
            "letter": "B",
            "content": "需根据特定的解剖部位"
        }, {
            "letter": "C",
            "content": "深层次的注射、需要的矫正程度高，选择中至高G’值、中至高内聚力的凝胶"
        }, {
            "letter": "D",
            "content": "浅层次的注射、需要的矫正程度低，选择低至中G’值、低至中内聚力的凝胶"
        }, {
            "letter": "E",
            "content": "面部动态区域，选择中等G’值、中至高内聚力的凝胶"
        }]
    }, {
        "topic": "（单选题）下面哪一项不属于理想面部填充剂的性质？ ",
        "label": "产品知识",
        "correct": "D",
        "options": [{
            "letter": "A",
            "content": "不良反应少"
        }, {
            "letter": "B",
            "content": "过敏机率低"
        }, {
            "letter": "C",
            "content": "效果自然"
        }, {
            "letter": "D",
            "content": "永久存在"
        }]
    }, {
        "topic": "（多选题）关于乔雅登<sup>®</sup>极致说法正确的的是 ",
        "label": "产品知识",
        "correct": "ACD",
        "options": [{
            "letter": "A",
            "content": "乔雅登<sup>®</sup>极致在提拉能力上依赖于更高的内聚力"
        }, {
            "letter": "B",
            "content": "乔雅登<sup>®</sup>极致在提拉能力上依赖于更高的弹性"
        }, {
            "letter": "C",
            "content": "乔雅登<sup>®</sup>极致和瑞蓝丽缇的头对头实验中，在治疗后第12个月，71.4%的测试者点名偏好使用乔雅登极致®进行鼻唇沟注射"
        }, {
            "letter": "D",
            "content": "乔雅登<sup>®</sup>极致和瑞蓝丽缇的头对头实验中，在此项12个月的测试者研究中，与瑞蓝丽缇相比，乔雅登极致®的长期有效性得到了证实"
        }]
    }, {
        "topic": "（多选题）决定透明质酸填充剂产品特性的因素有：",
        "label": "产品知识",
        "correct": "ABCD",
        "options": [{
            "letter": "A",
            "content": "透明质酸浓度"
        }, {
            "letter": "B",
            "content": "生产工艺"
        }, {
            "letter": "C",
            "content": "交联剂种类"
        }, {
            "letter": "D",
            "content": "交联透明质酸的含量"
        }]
    }, {
        "topic": "（多选题）如下说法正确的是 ",
        "label": "产品知识",
        "correct": "ABCD",
        "options": [{
            "letter": "A",
            "content": "乔雅登<sup>®</sup>采用HYLACROSS™技术生产出高浓度高交联度的均质化凝胶，"
        }, {
            "letter": "B",
            "content": "HYLACROSS™技术生产的凝胶拥有了三维立体的稳定结构，内聚力更高，不易被降解，维持时间更长"
        }, {
            "letter": "C",
            "content": "乔雅登<sup>®</sup>系列是首个被美国FDA批准有临床数据表明疗效长达一年的玻尿酸填充剂"
        }, {
            "letter": "D",
            "content": "乔雅登<sup>®</sup>极致和乔雅登<sup>®</sup>雅致重复治疗可使褶皱改善持续时间达18-21个月"
        }]
    }, {
        "topic": "（单选题）以下哪个竞品主要跟极致对标：",
        "label": "雅计划院内执行",
        "correct": "C",
        "options": [{
            "letter": "A",
            "content": "铂金瑞蓝"
        }, {
            "letter": "B",
            "content": "艾莉薇"
        }, {
            "letter": "C",
            "content": "Fillmed"
        }, {
            "letter": "D",
            "content": "公主"
        }]
    }, {
        "topic": "（多选题）乔雅登专场沙龙目标必备包含：",
        "label": "沙龙十步法",
        "correct": "AB",
        "options": [{
            "letter": "A",
            "content": "乔雅登单当日全院总支数"
        }, {
            "letter": "B",
            "content": "乔雅登当日每位咨询支数及套餐数"
        }, {
            "letter": "C",
            "content": "全院业绩目标"
        }, {
            "letter": "D",
            "content": "制定全院乔雅登总金额"
        }]
    }, {
        "topic": "（单选题）关于乔雅登<sup>®</sup>雅致说法正确的的是 ",
        "label": "产品知识",
        "correct": "C",
        "options": [{
            "letter": "A",
            "content": "颗粒均一"
        }, {
            "letter": "B",
            "content": "维持时间长达6个月"
        }, {
            "letter": "C",
            "content": "与注射层次匹配的支撑性"
        }, {
            "letter": "D",
            "content": "适合深层次的注射"
        }, {
            "letter": "E",
            "content": "组织融合性不如乔雅登<sup>®</sup>极致"
        }]
    }, {
        "topic": "（单选题）下列哪项不是乔雅登<sup>®</sup>系列的生产步骤？",
        "label": "产品知识",
        "correct": "E",
        "options": [{
            "letter": "A",
            "content": "交联"
        }, {
            "letter": "B",
            "content": "平衡"
        }, {
            "letter": "C",
            "content": "纯化"
        }, {
            "letter": "D",
            "content": "灭菌"
        }, {
            "letter": "E",
            "content": "诱导"
        }]
    }, {
        "topic": "（多选题）疫情期间医美机构专场活动关注的两大命题是 ",
        "label": "新开机构",
        "correct": "BD",
        "options": [{
            "letter": "A",
            "content": "新客招募"
        }, {
            "letter": "B",
            "content": "经营性现金流"
        }, {
            "letter": "C",
            "content": "利润考核"
        }, {
            "letter": "D",
            "content": "高价值客户管理"
        }]
    }]
}